### PR TITLE
feat: `serde::redacted` convenience `serialize_with` - serialize without exposing

### LINKED ISSUE #45: Add convenience `serialize_with` function to Serialize data without exposing it
### Discussed in https://github.com/eopb/redact/discussions/44

<div type='discussions-op-text'>

<sup>Originally posted by **8de2fdb0** November  2, 2023</sup>
regarding:
> Since serialization can expose the enclosed secret it is only possible to implement Serialize ....

Why can serialize expose the secret?

Can't you implement serialize without exposing the secret ?

https://serde.rs/impl-serialize.html

Maybe I am missing something but if I can't manipulate how serialize gets or gets not access to the secret that limits the scope of this crate a lot.
</div>

<div type='discussions-op-text'>

<sup>Originally posted by **eopb** November  3, 2023</sup>
> Can't you implement serialize without exposing the secret?

Your use case is a little different from mine. I'd like to understand why you're interested in serializing data without exposing the secret?

[`expose_secret`] isn't very special. You can write your own `serialize_with = "redacted"` version that does not expose the secret like this.

```rust
pub fn redacted<S: Serializer, T>(
    secret: &Secret<T>,
    serializer: S,
) -> Result<S::Ok, S::Error> {
    format!("{secret:?}").serialize(serializer)
}

#[derive(Serialize)]
struct Test {
    #[serde(serialize_with = "redacted")]
    field: Secret<String>,
}

let to_serialize = Test {
    field: Secret::from("hello"),
};

let serialized = serde_json::to_string(&to_serialize).unwrap();

assert_eq!(
    serialized,
    r#"{"field":"[REDACTED alloc::string::String]"}"#
)
```

Doing this would prevent you from `Deserialize`ing back into your original type since the required data from the original type has been redacted.

If that's something that would be useful to you, I'd be happy to include it in `redact` for convenience.

[`expose_secret`]: https://docs.rs/redact/latest/redact/fn.expose_secret.html
</div>

### PR DESCRIPTION
**Pull request by eopb**
resolves #45 

# Todo
- [x] Document function with rustdoc
- [x] Update serde section in `README.md`

### CODE REVIEW

**Comment by 8de2fdb0** [comment]
Maybe call it `redact_secret`, that would be more in line with the existing `expose_secret` function.

And thanks for adding that.

**Comment by eopb** [comment]
> Maybe call it `redact_secret`, that would be more in line with the existing `expose_secret` function.
> 
> And thanks for adding that.

Good idea. I prefer that

**Comment by 8de2fdb0** [comment]
still thinking about it ?

**Comment by eopb** [comment]
> still thinking about it ?

Hey, yes. I've just put this on the back burner since life's been hectic.

I still need to update the name and add some documentation. I'll probably get to it in the coming weeks. If you'd like, please feel free to pick it up and open a PR.

**Pull request merged**
